### ISSUE TITLE
【バグ】ヘッダーの検索窓に数字や、商品にない文字を入れるとエラーが起こる

### ISSUE THREAD

**Issue by 223yu** [gifu-revengers/dwc_team_development-#110]
確認した状況は下記のような感じです。
（私の現在のDB）
- メロンケーキ2
- ケーキ2
- ケーキ3
- ケーキ4
- ケーキ5

（試した語句）
- ケーキ　⇨　OK
- 1　⇨　undefined method `is_hira?' for "1":String Did you mean? is_a?
- レモン　⇨　undefined method `is_hira?' for "レモン":String Did you mean? is_a?

**Comment by 223yu** [comment]
@Taniguchi1204 お忙しいところ申し訳ないのですが、一度ご確認をいただいてもよろしいでしょうか。。。

**Comment by Taniguchi1204** [comment]
おそらく、gemのmiyabiがローカルで入っていないのかもしれません
一度bundle installして再度試してみてもらってもよろしいですか？

**Comment by 223yu** [comment]
すみません。bundle installしたらエラー起きなくなりました。。。
ただ、ひらがな検索ができなくて、また明日相談させてください。

**Comment by Taniguchi1204** [comment]
すいません、自分の説明不足だったと思います。
item tableにローマ字変換した文字を保存するカラムを追加しています。
itemを新規投稿した際にそちらのカラムにローマ字が保存されるようにしていますので
プルする前に保存してあるitemは検索出来ないかと思いますのでrails db:migrateかrails db:migrate:resetをした後に新規投稿をするかseedにもローマ字保存を追加しているのでrails db:seedをすれば検索出来るかと思います。

**Comment by 223yu** [comment]
@Taniguchi1204 理解できず申し訳ありませんでした。。。
確認したところ「ケーキ」で登録すると、「keki」でローマ字保存されるようです。
seeds.rbを修正したのでコミットしています。
