### ISSUE TITLE
軽微な修正

### ISSUE THREAD

**Issue by 223yu** [gifu-revengers/dwc_team_development-#57]
@pukuku 
#13 会員詳細画面から #6 注文履歴一覧への遷移について、注文履歴詳細画面への遷移リンクになっているようですので、修正をお願いします。

`<%= link_to "注文履歴一覧を見る",admin_order_path(@customer.id),class: "btn btn-primary btn-sm" %>`
を
`<%= link_to "注文履歴一覧を見る",admin_orders_path(customer_id: @customer.id),class: "btn btn-primary btn-sm" %>`
に変更していただくとうまういくのでは無いかと思うのですが、ならなかったらすみません！

**Comment by 223yu** [comment]
@pukuku  issueを追加したのでご確認をお願いします！

**Comment by pukuku** [comment]
@223yu ローカルで修正しておりますので、現在作業中のところが終わり次第プッシュします。
ありがとうございます！
