### ISSUE TITLE
[TOP]軽微な修正

### ISSUE THREAD

**Issue by pukuku** [gifu-revengers/dwc_team_development-#71]
@Taniguchi1204 
トップのジャンル検索の追加ありがとうございます！
renderですが、ディレクトリがhomesになるかと思います！
<%= render "public/items/genre_search", genres: @genres %>
↓
<%= render "public/homes/genre_search", genres: @genres %>

**Comment by Taniguchi1204** [comment]
@pukuku 
気づきありがとうございます
すいません、写し変える時に保存先を間違ってました
修正します！！

**Comment by Taniguchi1204** [comment]
@pukuku 
itemsのディレクトリにgenre_searchを移動しようかと思いますが問題ありませんか？

**Comment by Taniguchi1204** [comment]
@pukuku 
申し訳ございません、勘違いをしていたので確認したいのですが、ジャンル検索はtop画面、商品一覧画面、商品詳細画面で表示しているので、itemsディレクトリで作genre_searchを作成していたみたいなのですが、homesディレクトリに移動した方がいいと言う事でしょうか？

**Comment by 223yu** [comment]
横からすみません。publicにはitemsというフォルダがなくて、作成いただいたpartialはhomes/_genre_search.html.erbとなっていたので、renderの記述もそうした方がいいということだと思います！
developからpullしたら↑のような感じになってました！

**Comment by Taniguchi1204** [comment]
@pukuku @223yu 
色々と申し訳ございません
改めて見返した所、isuue毎にpushするためにファイルを移動して変なことになってました。修正します！！

**Comment by 223yu** [comment]
@Taniguchi1204 ありがとうございます！ローカルは修正して進めてるので、ゆっくりで大丈夫です！

**Comment by Taniguchi1204** [comment]
@223yu @ @pukuku 
では、ふくさんのご提示いただいた通りrenderの部分をhomesに変更します。
これからプルリクする商品一覧と商品詳細も同様に変更してpushします！！
お手数お掛けして申し訳ございません！！

**Comment by pukuku** [comment]
確認しました！
