### ISSUE TITLE
[会員]注文履歴一覧の並び順

### ISSUE THREAD

**Issue by pukuku** [gifu-revengers/dwc_team_development-#89]
注文日が新しい順（idの降順）に並べた方が見やすいかなと思いました！
    @orders = Order.where(customer_id: current_customer.id).order(id: :desc)

**Comment by pukuku** [comment]
以前のミーティングで、itemの名前の表示法についてご質問があったかと思いますが、私ならこう書くかなというものも共有しておきます！
あくまでも「私は」なので今のままでも問題ないと思います！

◆コントローラー
  def index
    @orders = Order.where(customer_id: current_customer.id).order(id: :desc)
  end

◆ビュー（該当部分抜粋）
          <% @orders.each do |order| %>
            **<% @order_details = OrderDetail.where(order_id: order.id) %>**
            <tr>
：
：
              <td>
                **<% @order_details.each do |order_detail| %>
                  <div><%= Item.find(order_detail.item_id).name %></div>
                <% end %>**
              </td>
：
：
            </tr>
          <% end %>

**Comment by 223yu** [comment]
@pukuku ありがとうございます！
ビュー側でwhereやfindを使うという思考が全くなかったです！
こっちのがスッキリしますね。余裕があったら修正しようと思います！
